package com.kspt.exchangetrading.models.util.enums;

public enum RequestType {
    OPEN_BROCKERAGE_ACCOUNT,
    CLOSE_BROCKERAGE_ACCOUNT,
    MAKE_BROKER_AGREEMENT,
    EXTEND_BROKER_AGREEMENT,
    BREAK_BROKER_AGREEMENT,
    EXCHANGE_MONEY_TO_STOCKS,
    EXCHANGE_STOCKS_TO_MONEY
}
