DROP TABLE PERSON_TYPE CASCADE;
DROP TABLE REQUEST_TYPE CASCADE;
DROP TABLE CURRENCY CASCADE;
DROP TABLE VALIDITY CASCADE;
DROP TABLE ADMIN CASCADE;
DROP TABLE CLIENT CASCADE;
DROP TABLE BROKER CASCADE;
DROP TABLE REQUEST CASCADE;
DROP TABLE AGREEMENT CASCADE;
DROP TABLE BROKERAGE_ACCOUNT CASCADE;

CREATE TABLE PERSON_TYPE
(
    id   BIGSERIAL PRIMARY KEY NOT NULL,
    type VARCHAR(10)           NOT NULL
);

CREATE TABLE REQUEST_TYPE
(
    id   BIGSERIAL PRIMARY KEY NOT NULL,
    type VARCHAR(30)           NOT NULL
);

CREATE TABLE CURRENCY
(
    id   BIGSERIAL PRIMARY KEY NOT NULL,
    type VARCHAR(6)           NOT NULL
);

CREATE TABLE VALIDITY
(
    id   BIGSERIAL PRIMARY KEY NOT NULL,
    type VARCHAR(10)           NOT NULL
);

CREATE TABLE ADMIN
(
    id      BIGSERIAL PRIMARY KEY NOT NULL,
    name    VARCHAR(30)           NOT NULL,
    surname VARCHAR(30)           NOT NULL
);

CREATE TABLE CLIENT
(
    id      BIGSERIAL PRIMARY KEY NOT NULL,
    name    VARCHAR(30)           NOT NULL,
    surname VARCHAR(30)           NOT NULL
);

CREATE TABLE BROKER
(
    id      BIGSERIAL PRIMARY KEY NOT NULL,
    name    VARCHAR(30)           NOT NULL,
    surname VARCHAR(30)           NOT NULL
);

CREATE TABLE REQUEST
(
    id          BIGSERIAL PRIMARY KEY NOT NULL,
    description VARCHAR(150),
    date        TIMESTAMP WITH TIME ZONE
);

CREATE TABLE AGREEMENT
(
    id         BIGSERIAL PRIMARY KEY not null,
    client     BIGINT                NOT NULL REFERENCES CLIENT,
    broker     BIGINT                NOT NULL REFERENCES BROKER,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date   TIMESTAMP WITH TIME ZONE
);

CREATE TABLE BROKERAGE_ACCOUNT
(
    id            BIGSERIAL PRIMARY KEY not null,
    number        BIGINT                NOT NULL,
    money         BIGINT                NOT NULL,
    currency      INT                   NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE
);